# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: Adoptium-8
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM eclipse-temurin:9

LABEL org.opencontainers.image.authors="noreplay@noreply.org"
LABEL org.opencontainers.image.vendor="KKP"

ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y --no-install-recommends bash curl wget tzdata ca-certificates fontconfig libfreetype6 && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    useradd -d /home/container container

USER container
ENV  USER=container
ENV  HOME=/home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
