name: delete-runs
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch: {}
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 执行脚本
        uses: actions/github-script@v7
        env:
          SHA: "${{env.parentSHA}}"
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const script = require('./scripts/delete-runs.js')
            await script({github, context, core})
