name: delete-untagged
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch: {}
  push:
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 执行脚本
        uses: actions/github-script@v7
        env:
          SHA: "${{env.parentSHA}}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/delete-untagged.js')
            await script({github, context, core})
