# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: Adoptium-17
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM eclipse-temurin:17-alpine

LABEL org.opencontainers.image.authors="noreplay@noreply.org"
LABEL org.opencontainers.image.vendor="KKP"

RUN apk --no-cache update && \
    apk --no-cache add bash curl wget tzdata ca-certificates && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
