name: delete-untagged
on:
  schedule:
    - cron: "5 4 */3 * *"
  workflow_dispatch: {}
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const respPackages = await github.request("GET /orgs/{org}/packages",
              {
                package_type: "container",
                org: "${{ env.OWNER }}"
              }
              );
            for (pack of respPackages.data){
              const packName=pack.name;
              const response = await github.request(`GET /orgs/${{ env.OWNER }}/packages/container/${packName}/versions`,
                { per_page: 30 });
              for(version of response.data) {
                  if (version.metadata.container.tags.length == 0) {
                      console.log("delete " + version.id)
                      const deleteResponse = await github.request(`DELETE /orgs/${{ env.OWNER }}/packages/container/${packName}/versions/${version.id}`, { });
                      console.log("status " + deleteResponse.status)
                  }
              }
            }

        env:
          OWNER: ${{ github.repository_owner }}
