# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: BellSoftLiberica-17 With Py3
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM bellsoft/liberica-openjdk-debian:17

LABEL org.opencontainers.image.authors="noreplay@noreply.org"
LABEL org.opencontainers.image.vendor="KKP"

RUN apt update && \
    apt install -y --no-install-recommends bash curl wget tzdata ca-certificates python3 python3-pip && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
