# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: AmazonCorretto-11
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM amazoncorretto:11-alpine

LABEL org.opencontainers.image.authors="noreplay@noreply.org"
LABEL org.opencontainers.image.vendor="KKP"

RUN apk --no-cache update && \
    apk --no-cache add bash curl wget tzdata ca-certificates && \
    adduser -d /home/container -m container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
