# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: Tencent Kona-11
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM alpine
# 第一步 下载
RUN apk update && \
    apk add wget curl unzip tar gzip ca-certificates
RUN curl https://api.github.com/repos/Tencent/TencentKona-11/releases/latest \
    | grep browser_download_url \
    | grep linux \
    | grep -v md5 \
    | cut -d '"' -f 4 \
    | wget -O /tmp/openjdk.tar.gz -i -

RUN mkdir -p /opt/java/kona; \
    cd /opt/java/kona; \
    tar -xf /tmp/openjdk.tar.gz --strip-components=1; \
    rm -fr man sample src.zip; \
    rm -rf /tmp/openjdk.tar.gz;
# 第二步 安装
FROM debian

LABEL org.opencontainers.image.authors="noreplay@noreply.org"
LABEL org.opencontainers.image.vendor="KKP"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

COPY --from=0 /opt/java/kona /opt/java/kona

ENV JAVA_HOME=/opt/java/kona \
    PATH="/opt/java/kona/bin:$PATH"

RUN apt update && \
    apt install -y --no-install-recommends bash curl wget tzdata && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
