# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: AdoptOpenJDK-11-Hotspot
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM adoptopenjdk/openjdk11:alpine-slim

LABEL org.opencontainers.image.authors="noreplay@noreply.org"
LABEL org.opencontainers.image.vendor="KKP"

RUN apk --no-cache update && \
    apk --no-cache add bash curl wget tzdata ca-certificates && \
    adduser -D -h /home/container container

USER container
ENV  USER=container
ENV  HOME=/home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
