services:
  ffmpeg-over-ip:
    image: ffmpeg-over-ip:latest
    container_name: ffmpeg-over-ip-server
    restart: unless-stopped
    ports:
      - "5050:5050"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./config:/etc/ffmpeg-over-ip:ro
    environment:
      - TZ=Asia/Shanghai
