# ----------------------------------
# Pterodactyl Steam Game Dockerfile
# Game: ARK Survival Evolved
# Minimum Panel Version: 0.7.0
# ----------------------------------
FROM ghcr.io/parkervcp/steamcmd:debian

COPY ./entrypoint.sh /entrypoint.sh
CMD [ "/bin/bash", "/entrypoint.sh" ]