name: 构建 builds-stack-e5sub 镜像
on:
  push:
    paths:
      - builds/stack/e5sub/Dockerfile
      - builds/stack/e5sub/entrypoint.sh
      - .github/workflows/builds-stack-e5sub.yml
  schedule:
    - cron: 30 5 * * 5
  workflow_dispatch: {}
permissions:
  packages: write
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-builds-stack-e5sub:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 登陆到 DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 构建 builds-stack-e5sub 镜像
        uses: docker/build-push-action@v6
        with:
          context: builds/stack/e5sub
          file: builds/stack/e5sub/Dockerfile
          push: true
          tags: ghcr.io/kitkat-starter/stack:e5sub
          outputs: type=image,push=true,compression=zstd,compression-level=3
          cache-from: type=gha
          cache-to: type=gha,mode=max
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-builds-stack-e5sub
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images
          builds/stack/e5sub/e5sub.yml
