name: delete-untagged
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch: {}
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        env:
          SHA: "${{env.parentSHA}}"
        with:
          script: |
            const script = require('./path/to/script.js')
            await script({github, context, core})
