name: 构建 emdm-percona-mongodb 镜像
on:
  push:
    paths:
      - emdm/percona-mongodb/Dockerfile
      - emdm/percona-mongodb/entrypoint.sh
      - .github/workflows/emdm-percona-mongodb.yml
  schedule:
    - cron: 30 5 * * 5
  workflow_dispatch: {}
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-emdm-percona-mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: 登陆到 DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 构建 emdm-percona-mongodb 镜像
        uses: docker/build-push-action@v3
        with:
          context: emdm/percona-mongodb
          file: emdm/percona-mongodb/Dockerfile
          push: true
          tags: ghcr.io/kitkat-starter/suck:percona-mongodb
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-emdm-percona-mongodb
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images emdm/percona-mongodb/percona-mongodb.yml
