name: 构建 emdm-clash 镜像
on:
  push:
    paths:
      - emdm/clash/Dockerfile
      - emdm/clash/entrypoint.sh
      - .github/workflows/emdm-clash.yml
  schedule:
    - cron: 30 5 * * 5
  workflow_dispatch: {}
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-emdm-clash:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: 登陆到 DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 构建 emdm-clash 镜像
        uses: docker/build-push-action@v2
        with:
          context: emdm/clash
          file: emdm/clash/Dockerfile
          push: true
          tags: ghcr.io/kitkat-starter/suck:clash
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-emdm-clash
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images emdm/clash/clash.yml
