name: 构建 emdm-sniproxy 镜像
on:
  push:
    paths:
      - emdm/sniproxy/Dockerfile
      - emdm/sniproxy/entrypoint.sh
      - .github/workflows/emdm-sniproxy.yml
  schedule:
    - cron: 30 5 * * 5
  workflow_dispatch: {}
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-emdm-sniproxy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 登陆到 DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 构建 emdm-sniproxy 镜像
        uses: docker/build-push-action@v5
        with:
          context: emdm/sniproxy
          file: emdm/sniproxy/Dockerfile
          push: true
          tags: ghcr.io/kitkat-starter/suck:sniproxy
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-emdm-sniproxy
    steps:
      - name: 检出代码
        uses: actions/checkout@v5
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images emdm/sniproxy/sniproxy.yml
