name: 构建 gsipct-steam-source-common 镜像
on:
  push:
    paths:
      - gsipct/steam/source-common/Dockerfile
      - gsipct/steam/source-common/entrypoint.sh
      - .github/workflows/gsipct-steam-source-common.yml
  schedule:
    - cron: 15 6 5 * *
  workflow_dispatch: {}
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-gsipct-steam-source-common:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: 登陆到 DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 构建 gsipct-steam-source-common 镜像
        uses: docker/build-push-action@v2
        with:
          context: gsipct/steam/source-common
          file: gsipct/steam/source-common/Dockerfile
          push: true
          tags: ghcr.io/kitkat-starter/gsipct-steam:source-common
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-gsipct-steam-source-common
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images gsipct/steam/source-common/source-common.yml
